### ISSUE TITLE
Bot with cases: Crash of Bot doesn't result in negativ test

### ISSUE THREAD

**Issue by mpw-wwu** [oTree-org/oTree#67] opened 2019-11-25 12:53 UTC
Let's say you have the following code in your testing bot:

```
cases = [
              {
                    'contribution_for_each_player': [0] * 7,
                    'contribution_must_fail: [
                          ['A'] * 7,
                          ['2$'] * 7,
                    ]
              },
              {
                    'contribution_for_each_player': [1] * 7,
              },

[...]

for must_fail in self.case.get('contribution_must_fail'):
    yield SubmissionMustFail(pages.X, dict(contribution = must_fail[self.player.id_in_group-1]))
yield yield pages.X, dict(contribution = contribution_for_each_player[self.player.id_in_group-1])
```

This will crash in the second round with this sort of error, because the return value for get is None if the dict entry doesn't exist:

```
TypeError: 'NoneType' object is not iterable
```

But the testing engine doesn't detect it:

```
$ otree browser_bots Extraround7_7_BOTTEST
Extraround7_7_BOTTEST   7 participants...[15924:15924:1125/133953.614519:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
...finished in 14.4 seconds
Extraround7_7_BOTTEST   7 participants...[16642:16642:1125/134008.169474:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
...finished in 1.9 seconds
Total: 16.3 seconds
```

Just from the very short run time for the second case, you can tell that something is going wrong. Otree shouldn't catch the exception and fail the test.

Workaround by the way is to give an empty array as default value:
```
for must_fail in self.case.get('contribution_must_fail', []):
```

Best,
Matthias

**Comment by oTree-org** [comment] 2019-11-25 13:08
Excellent catch :) this is kind of a "corner case" of the bot system, caused by this line here:

https://github.com/oTree-org/otree-core/blob/0252476e05980d465f766c2f5e0733d275b517db/otree/bots/bot.py#L185

I'll see if there is a different implementation that can report this error more accurately. Thanks for reporting.

**Comment by mpw-wwu** [comment] 2019-11-25 13:16
I don't really understand your explanation in lines 186ff. If there is any kind of exception in the bot code, the bot should fail. I don't see any case where this wouldn't be the expected behaviour. So let me ask the question, why do you suppress exceptions at all? I understand the concept of catching them and adding better explanations, but I don't see any case where an exception in the bot should be catched and suppressed. 

But I'm relativly new to otree, so maybe I missed a case in my thoughts.

**Comment by oTree-org** [comment] 2019-11-25 13:24
That specific error needs to be caught because of how generators work. We are handling the case where the play_round function doesn't contain any yield statements. But actually I just found a simpler solution that can eliminate that code. I implemented it locally and it will be in the next release.

**Comment by oTree-org** [comment] 2019-11-25 13:25
(It relates more to the comment on line 181, but anyway it's moot now that I have the new solution)

**Closed by oTree-org** 2019-11-25 13:25 UTC

**Comment by mpw-wwu** [comment] 2019-11-25 13:38
Cool, thank you for immediately addressing this.

By the way, this repository seems to only contain the released version of otree. Is there some kind of developer repository, or is that private?
